config/routes.rb
Rails.application.routes.draw do
  root 'surveys#index'
  resources :surveys
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  has_many :answers
  accepts_nested_attributes_for :answers, allow_destroy: true

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:show, :edit, :update, :destroy]

  # GET /surveys
  # GET /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1
  # GET /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys
  # POST /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: 'Survey was successfully created.' }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1
  # PATCH/PUT /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: 'Survey was successfully updated.' }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: 'Survey was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def survey_params
      params.require(:survey).permit(:name, questions_attributes: [:id, :content, :_destroy, answers_attributes: [:id, :content, :_destroy]])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
      link_to(name, '#', class: "add_fields answer_link", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NestedModelForms</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: "text-center white_text" %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/surveys/_answer_fields.html.erb
<fieldset>
  <%= f.label :content, "Answer" %>
  <%= f.text_field :content %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove", '#', class: "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <%= f.fields_for :questions do |builder| %>
    <%= render "question_fields", f: builder %>
  <% end %>
  
  <%= link_to_add_fields "Add Question", f, :questions %>
  <br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/_question_fields.html.erb
<fieldset class="qArea">
  <%= f.label :content, "Question" %><br>
  <%= f.text_area :content %><br>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove Question" %>
  <br>
  <%= f.fields_for :answers do |builder| %>
    <%= render "answer_fields", f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answers %> <!--helper-->
</fieldset>

app/views/surveys/edit.html.erb
<h1 class="text-center white_text">Edit Survey</h1>

<div class="page_body edit_page">
  <%= render 'form' %>
</div>

app/views/surveys/index.html.erb
<h1 class="text-center white_text">Surveys</h1>
<div class="page_body text-center">
  <div class="inner">
    <% @surveys.each do |survey| %>
      <div class="article">
        <h3><%= link_to survey.name, survey %></h3>
        <%= pluralize(survey.questions.size, "Question") %>
      </div>
      <hr>
    <% end %>
  </div>

  <h4><%= link_to 'New Survey', new_survey_path, class: "underline" %></h4>
  <br>
</div>

app/views/surveys/new.html.erb
<h1 class="text-center white_text">New Survey</h1>

<div class="page_body edit_page">
  <%= render 'form' %>
</div>

app/views/surveys/show.html.erb
<h1 class="text-center white_text"><%= @survey.name %></h1>
<div class="page_body">
  <ol class="questions">
  <% @survey.questions.each do |question| %>
    <li>
      <%= question.content %>
      <ol class="answers">
        <% question.answers.each do |answer| %>
          <li><%= answer.content %></li>
        <% end %>
      </ol>
    </li>
  <% end %>
  </ol>
</div>
<div class="text-center white_text">
  <h4>
    <%= link_to 'Edit', edit_survey_path(@survey), class: "white_text" %> |
    <%= link_to 'Back', surveys_path, class: "white_text" %>
  </h4>
</div>